language: node_js

node_js:
- stable

dist: xenial
sudo: false

notifications:
  email: false

script:
- yarn install
- yarn run lint
- yarn run build
- yarn run test

deploy:
- provider: npm
  email: web@goertler.email
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master

