name: publish

on: release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: setup
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: install
      run: yarn install

    - name: lint
      run: yarn run lint
      env:
        CI: true

    - name: build
      run: yarn run build
      env:
        CI: true

    - name: test
      run: yarn run test

    - name: publish
      run: yarn publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        
